[workspace]
members = ["classfile", "jvm", "jvm-bytecode", "jvm-class-proto", "jvm-types", "rustjava-runtime"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/dlunch/RustJava"

[workspace.dependencies]
anyhow = { version = "^1.0", default-features = false }
async-recursion = { version = "^1.0", default-features = false }
async-trait = { version = "^0.1", default-features = false }
bytemuck = { version = "^1.25", default-features = false, features = ["extern_crate_alloc"] }
dyn-clone = { version = "^1.0", default-features = false }
dyn-hash = { version = "^1.0", default-features = false }
hashbrown = { version = "^0.17", features = ["default-hasher"], default-features = false }
nom = { version = "^8.0", default-features = false, features = ["alloc"] }
parking_lot = { version = "^0.12", default-features = false }
tracing = { version = "^0.1", default-features = false, features = ["attributes"] }

tokio = { version = "^1.52", features = ["macros"] }

classfile = { path = "classfile", version = "0.2.0" }
jvm = { path = "jvm", version = "0.2.0" }
jvm-bytecode = { path = "jvm-bytecode", version = "0.2.0" }
jvm-class-proto = { path = "jvm-class-proto", version = "0.2.0" }
jvm-types = { path = "jvm-types", version = "0.2.0" }
rustjava-runtime = { path = "rustjava-runtime", version = "0.2.0" }
test-utils = { path = "test-utils" }

[package]
name = "RustJava"
description = "An embeddable JVM and Java runtime implemented in Rust"
exclude = ["docs"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "rust_java"

[[bin]]
name = "rust_java"
path = "src/main.rs"

[dependencies]
async-trait = { workspace = true }
bytemuck = { workspace = true }

anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "^0.3", features = ["env-filter"] }

jvm = { workspace = true }
jvm-bytecode = { workspace = true }
jvm-class-proto = { workspace = true }
rustjava-runtime = { workspace = true }

[dev-dependencies]
test-utils = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true, features = ["rt", "time"] }
